title: danemacmillan
description: This is where Dane MacMillan has written things down.
author: Dane MacMillan
url: https://danemacmillan.com
email: ""
permalink: /:title/

theme: minima
show_excerpts: true
header_pages:
  - about.md
disqus:
  shortname: danemacmillan

google_analytics: UA-133416235-1

