title: danemacmillan
description: This is where Dane MacMillan has written things down.
url: https://danemacmillan.com
permalink: /:title/

theme: minima
show_excerpts: false
header_pages:
  - about.md
disqus:
  shortname: danemacmillan

google_analytics: UA-133416235-1

minima:
  social_links:
    twitter: dane_macmillan
    github: danemacmillan
    instagram: danemacmillan
    linkedin: danemacmillan
    rss: rss

